# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release-latest

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
   # - uses: "marvinpinto/action-automatic-releases@latest"
   #   with:
   #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
   #     automatic_release_tag: "latest"
   #     prerelease: false
    #    files: |
     #     build/libs/*.jar
          
    - name: Automatic Semver Release
      uses: rui-costa/action-automatic-semver-releases@1.0.0-final
      with:
        # Secret token from GitHub
        TOKEN: "${{ secrets.GITHUB_TOKEN }}" 
        # Which version you want to increment? Use MAJOR, MINOR or PATCH
        SEMVER: MAJOR
        # The name of your main branch
        MAIN_BRANCH: master
