# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release-latest

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Autotag
      # You may pin to the exact commit or the version.
      # uses: phish108/autotag-action@f36ee28f5ae9fed02e5b3477271a06eb3e94ac2c
      uses: phish108/autotag-action@1.1.37
      with:
        # the GH token to connect to github from the action
        github-token: ${{ github.token }}
        # check if the action would succeed
        dry-run: FALSE
        # which part of the semver needs to be updated?
        bump: patch
        # force to tag a specific branch
       # branch: # optional, default is 
        # use version prefix
        with-v: FALSE
        # provide the names from which branches to release
        release-branch: master
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          build/libs/*.jar
      
